# Generated by Django 4.0.4 on 2022-04-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('company_description', models.TextField()),
                ('company_website', models.CharField(max_length=500)),
                ('company_logo', models.ImageField(upload_to='company_logos/')),
                ('company_type', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
