# Generated by Django 4.0.4 on 2022-05-17 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_cumulativeviate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('current_salary', models.IntegerField()),
                ('expected_salary', models.IntegerField()),
                ('experience', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('languages', models.CharField(max_length=50)),
                ('allow_search', models.BooleanField(default=True)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_description', models.TextField()),
                ('company_website', models.CharField(max_length=50)),
                ('company_email', models.CharField(max_length=50)),
                ('company_phone', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=50)),
                ('company_team_size', models.CharField(max_length=50)),
                ('company_logo', models.ImageField(blank=True, upload_to='company_logos')),
                ('company_cover_image', models.ImageField(blank=True, upload_to='company_cover_images')),
                ('bio', models.TextField()),
                ('establishment_date', models.DateField(auto_now_add=True)),
                ('city', models.CharField(max_length=50)),
                ('find_on_map', models.CharField(max_length=50)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('facebook', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('google_plus', models.CharField(max_length=50)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('company_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
    ]
